[package]
name = "time-tests"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "baseline"
harness = false

[[bench]]
name = "benchmark"
harness = false

[dependencies]
time = { version = "0.3", features = ["macros", "formatting", "parsing"] }

[dev-dependencies]
criterion = "0.3"
